In [3]:
!pip install sumpy

In [4]:
"""goldbach_conjecture.ipynb"""

# Cell 01

import numpy as np
from sympy import prime

test_limit = 100

# Use a list comprehension to create an array of the first 'n' ODD primes
primes = np.array([prime(n) for n in range(2, test_limit)])

print(primes[:10])
print(primes[-10:])

[ 3  5  7 11 13 17 19 23 29 31]
[463 467 479 487 491 499 503 509 521 523]


In [5]:
# Cell 02 - Generate all pairs of primes (with repetition)

from itertools import combinations_with_replacement

prime_pairs = [*combinations_with_replacement(primes, 2)]

print(len(prime_pairs))

[*zip(prime_pairs[:5], prime_pairs[98:], prime_pairs[195:])]

4851


[((np.int64(3), np.int64(3)),
  (np.int64(5), np.int64(5)),
  (np.int64(7), np.int64(7))),
 ((np.int64(3), np.int64(5)),
  (np.int64(5), np.int64(7)),
  (np.int64(7), np.int64(11))),
 ((np.int64(3), np.int64(7)),
  (np.int64(5), np.int64(11)),
  (np.int64(7), np.int64(13))),
 ((np.int64(3), np.int64(11)),
  (np.int64(5), np.int64(13)),
  (np.int64(7), np.int64(17))),
 ((np.int64(3), np.int64(13)),
  (np.int64(5), np.int64(17)),
  (np.int64(7), np.int64(19)))]

In [6]:
# Cell 03 - Create a sorted array containing the unique sums of each prime pairs

summed_pairs = np.sort(np.unique(np.array([sum(pair) for pair in prime_pairs])))

print(summed_pairs[:10])
print(summed_pairs[-10:])

[ 6  8 10 12 14 16 18 20 22 24]
[1018 1020 1022 1024 1026 1030 1032 1042 1044 1046]


In [7]:
# Cell 04

"""
Determine which EVEN integers from 6 to test_limit (inclusive) are NOT in
the list of summed prime pairs. The numpy function setdiff1d() returns
any elements in the first array that are not also in the second array
"""

violations = np.setdiff1d(range(6, test_limit + 2, 2), summed_pairs)

print(f"Number of Goldbach violations up to {summed_pairs[-1]}: {len(violations)}")
if len(violations > 0):
    print(violations)

Number of Goldbach violations up to 1046: 0
